### ISSUE TITLE
setting up emailplsu error : permission denied

### ISSUE THREAD

**Issue by rioshaz** [joforce/JoforceCRM#119]
After entering mailbox settings, when i login to roundcube i get this error..
Permission denied

**Comment by smackrajue** [comment]
This may be due to less secure connection not enabled if you use Gmail. Steps to enable the less secure connection in your Gmail 

- Go to the "Less secure apps" section of my Account. - https://myaccount.google.com/lesssecureapps.
- Turn on Allow less secure apps. 
- Note: If your administrator has locked less secure app account access, this setting is hidden.)

If this is not Gmail needs to reconfigure the email settings.

**Comment by rioshaz** [comment]
@smackrajue but i am useing my own webmail ... no gmail man... so why it doesnt work
