### ISSUE TITLE
PDF Maker

### ISSUE THREAD

**Issue by dfanaei** [joforce/JoforceCRM#94]
Hi, 
First, I would like to thank you for modifying the Vtiger in a way that is much better than what it initially was. There was lots of customization issues I was having with Vtiger unfortunately. 
and all the other ones such as yetiforce which has the most arrogant developers that simply don't realize there are lots of bugs with their system, just did not help with getting my project forward. 

Joforce works amazing! however, There are a couple of issues I would like to address. 

1. PDF Maker: 
I am trying to add more than one template of pdf for the invoice module. The reason being, sometimes when you try to sell to a client, you might not want to have certain fields shown, for example, the discount field. also, I am trying to add PDF report for custom modules. 
**Is there a way to do that at the moment?** I think being able to have more than one option of reporting template for each module is a necessity when it comes to sales. 
if this is not a quick fix, does the pdf maker from its4you work with joforce? 

2. Module Studio: 
So I am trying to relate the purchase order module to the Organization module as well. creating the field in the purchase order module for entering the account/organization works fine. However, when it comes to creating the list for purchase orders to show in the accounts, it is giving me an unknown error. so it doesn't update the account module. 
**are you aware of this problem?**

thank you so much in advance for the hardwork you have put into this, it looks amazing , especially if these 2 problems get fixed.

**Comment by Dinesh-JoForce** [comment]
I would firstly like to thank you for your time taken to have this issue addressed to us @dfanaei .

Your issues are noted and have been checked thoroughly 

1. PDF Maker:
Regarding Templates, we have restricted in it to a single template as of now. If you would like to have  multiple templates added we need to customize it . Currently, no third party extension would support JoForce. We are working towards the same and would have this fixed in future.

2. Module Studio: 
Sorry for the inconvenience caused.  We weren't aware about this issue and thank you have your issue listed . I had a check on the same and will have this fixed in our upcoming release.
